version: "3.8"
services:
  db:
    container_name: tracker-project-db
    image: postgres
    ports:
      - "5440:5432"
    environment:
      - "POSTGRES_USER=project"
      - "POSTGRES_PASSWORD=project"
    volumes:
      - /etc/postgresql:/var/log/postgresql:/var/lib/postgresql